export const GRAMMAR_EQUIVALENTS = [
    ["sin", "sins"],
    ["debt", "debts"],
    ["son", "sons"],
    ["child", "children"],
    ["brother", "brothers"],
    ["servant", "servants"],
    ["enemy", "enemies"],
    ["prophet", "prophets"],

    ["say", "says", "said", "saying", "answer", "answers", "answered", "reply", "replies", "replied", "speak", "speaks", "spoke", "spoken", "tell", "tells", "told"],
    ["do", "does", "did", "doing", "didst"],
    ["come", "comes", "came", "coming"],
    ["go", "goes", "went", "going"],
    ["see", "sees", "saw", "seen", "seeing"],
    ["hear", "hears", "heard", "hearing"],
    ["believe", "believes", "believed", "believing"],
    ["save", "saves", "saved", "saving"],
    ["heal", "heals", "healed", "healing"],

    ["thou", "thee", "ye", "you"],
    ["thy", "thine", "your"]
];

export const PROTECTED_TERMS = [
    "blessed",
    "happy",
    "kingdom",
    "reign",
    "gehenna",
    "hell",
    "hades",
    "aeon",
    "age",
    "age-long",
    "eternal",
    "slave",
    "servant",
    "spirit",
    "breath",
    "wind",
    "forgive",
    "release",
    "repent",
    "faith",
    "faithfulness",
    "trust",
    "poor",
    "destitute",
    "righteous",
    "just",
    "righteousness",
    "justice",
    "law",
    "torah",
    "mammon",
    "wealth",
    "money",
    "condemn",
    "judge",
    "saved",
    "miracle",
    "sign",
    "truly",
    "amen"
];

export const INTERPRETIVE_TERMS = [
    ["blessed", "happy", "blissful"],
    ["kingdom", "reign"],
    ["gehenna", "hell"],
    ["hades", "hell"],
    ["world", "cosmos"],
    ["human", "man", "humanity", "human beings"],
    ["evil", "wicked", "wicked man", "evil one"],
    ["hypocrite", "hypocrites", "charlatan", "charlatans", "playacting charlatan", "playacting charlatans"],
    ["falter", "stumble", "sin", "offend"],
    ["soul", "life"],
    ["heal", "cure", "make clean", "made clean"],
    ["rise", "arise", "stand up", "get up"],
    ["aeon", "age", "eternal", "age-long"],
    ["slave", "servant"],
    ["spirit", "breath", "wind"],
    ["forgive", "release", "let go"],
    ["faith", "faithfulness", "trust"],
    ["repent", "change heart", "change hearts", "change your heart", "change your hearts", "change mind", "change minds", "change your mind", "change your minds"],
    ["poor", "destitute"],
    ["righteous", "just"],
    ["righteousness", "justice"],
    ["law", "torah"],
    ["mammon", "wealth", "money"],
    ["condemn", "judge"],
    ["saved", "made whole"],
    ["miracle", "sign"],
    ["truly", "amen"],
    ["eternal life", "age-long life", "life of the age"],
    ["kingdom of heaven", "kingdom of the heavens"],
    ["poor in spirit", "destitute in spirit"]
];

export const LOW_SIGNAL_TERMS = [
    "man",
    "men",
    "person",
    "people",
    "thing",
    "things",
    "all",
    "there",
    "out",
    "up",
    "away",
    "forth",
    "also",
    "even",
    "indeed",
    "well",
    "rather",
    "very",
    "just",
    "only",
    "again",
    "upon",
    "unto",
    "while",
    "having",
    "own",
    "made",
    "make",
    "put",
    "let",
    "give",
    "come",
    "go",
    "get",
    "say",
    "says",
    "said",
    "saying",
    "behold",
    "look",
    "see",
    "O",
    "no",
    "not",
    "you",
    "Jesus"
];

export const PROTECTED_LOW_SIGNAL_EXCEPTIONS = [
    "Son of Man",
    "kingdom of heaven",
    "kingdom of the heavens",
    "life of the Age",
    "eternal life",
    "Son of God",
    "I AM",
    "truly I tell you",
    "amen I tell you"
];

export const COMMON_VERB_STEMS = [
    ["come", "comes", "came", "coming"],
    ["know", "knows", "knew", "known", "knowing"],
    ["take", "takes", "took", "taken", "taking"],
    ["want", "wants", "wanted", "wanting", "wish", "wishes", "wished", "desire", "desires", "desired"],
    ["make", "makes", "made", "making"],
    ["give", "gives", "gave", "given", "giving"],
    ["put", "puts", "putting"],
    ["let", "lets", "letting"],
    ["get", "gets", "got", "gotten", "getting"],
    ["look", "looks", "looked", "looking"],
    ["see", "sees", "saw", "seen", "seeing"],
    ["say", "says", "said", "saying"],
    ["go", "goes", "went", "gone", "going"],
    ["rise", "rises", "rose", "risen", "rising"],
    ["stand", "stands", "stood", "standing"]
];

export const COMMON_NOUNS = [
    "hand",
    "hands",
    "time",
    "hour",
    "hours",
    "day",
    "days",
    "way",
    "ways",
    "place",
    "places",
    "word",
    "words",
    "work",
    "works",
    "name",
    "names",
    "house",
    "household",
    "master",
    "lord",
    "others",
    "everything",
    "man",
    "men",
    "people",
    "person"
];

export const CRITICAL_WORDS = [
    "father",
    "son",
    "spirit",
    "kingdom",
    "gehenna",
    "hell",
    "hades",
    "aeon",
    "eternal",
    "life",
    "death",
    "judge",
    "judgment",
    "sin",
    "forgive",
    "repent",
    "faith",
    "believe",
    "truth",
    "love",
    "hate",
    "poor",
    "rich"
];
